// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYR1RAVgsaT4vzBaPxPTCABK3DNknaVo',
    appId: '1:770490909:web:cc5172b26b0fbd9f28bcf4',
    messagingSenderId: '770490909',
    projectId: 'taskhub-abc23',
    authDomain: 'taskhub-abc23.firebaseapp.com',
    storageBucket: 'taskhub-abc23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgo9UIj3vCZ-fDXXNaoHis7Up7svVsjJM',
    appId: '1:770490909:android:6cfae143883196c328bcf4',
    messagingSenderId: '770490909',
    projectId: 'taskhub-abc23',
    storageBucket: 'taskhub-abc23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiFVlM4Gtjw-VgYBHmzU_OFblqsBgiwxU',
    appId: '1:770490909:ios:4a8551b4e32a2b7d28bcf4',
    messagingSenderId: '770490909',
    projectId: 'taskhub-abc23',
    storageBucket: 'taskhub-abc23.appspot.com',
    iosBundleId: 'com.example.taskhubapp',
  );
}
